services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    volumes:
      - ./server/uploads:/app/uploads
    restart: always

  client:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - server
    restart: always
